name: BO3Tools
main: nl.rutgerkok.bo3tools.BO3Tools
version: 1.4
author: "Rutger Kok"
depend: ["TerrainControl", "WorldEdit"]
description: Bukkit plugin to help you working with the BO3 objects.
permissions:
  bo3tools.all:
    description: Use all BO3 tools.
    default: op
    children:
      bo3tools.exportbo3: true
      bo3tools.convertbo2: true
      bo3tools.convertallbo2: true
  bo3tools.exportbo3:
    description: Export your WorldEdit selection as a BO3.
  bo3tools.convertbo2:
    description: Convert a single BO2 to a BO3.
  bo3tools.convertallbo2:
    description: Convert all BO2 objects in one of the object folders to BO3 objects.
commands:
  exportbo3:
    description: "Export a WorldEdit selection to a BO3, (optionally) ignoring all air blocks."
    usage: "/<command> <bo3name> [--includeair] [--includetileentities] [--noleavesfix]"
    aliases: [export]
    permission: bo3tools.exportbo3
  convertbo2:
    description: "Convert a BO2 object to a BO3 object."
    usage: "/<command> <bo2name>"
    permission: bo3tools.convertbo2
  convertallbo2:
    description: "Converts all BO2 objects in one of the object folders to BO3 objects."
    usage: "/<command> [worldname/global]"
    permission: bo3tools.convertallbo2
